name: Generate Gallery

on:
  push:
    paths:
      - "images/tables/**"
  workflow_dispatch: # allow manual runs

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate gallery.json
        run: |
          echo "[" > gallery.json
          first=true
          for file in images/tables/*; do
            [ -f "$file" ] || continue
            ext="${file##*.}"
            name=$(basename "$file")
            title="${name%.*}"

            if [ "$ext" = "mp4" ]; then
              type="video"
            else
              type="image"
            fi

            if [ "$first" = true ]; then
              first=false
            else
              echo "," >> gallery.json
            fi

            # Notice: removed leading ./ in src
            echo "  { \"type\": \"$type\", \"src\": \"images/tables/$name\", \"title\": \"$title\" }" >> gallery.json
          done
          echo "]" >> gallery.json

      - name: Commit and push gallery.json
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add gallery.json
          git commit -m "Auto-update gallery.json" || echo "No changes"
          git push
