name: Generate Gallery

on:
  push:
    paths:
      - "images/tables/**"
  workflow_dispatch:

jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'Auto-update gallery.json')" 
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate gallery.json
        run: |
          echo "[" > gallery.json
          first=true
          for file in images/tables/*; do
            ext="${file##*.}"
            name=$(basename "$file")
            rawtitle="${name%.*}"

            # Replace underscores with spaces
            title=$(echo "$rawtitle" | sed 's/_/ /g')

            # Add spaces before capital letters (e.g. "PatagoniaRosewood" -> "Patagonia Rosewood")
            title=$(echo "$title" | sed 's/\([a-z]\)\([A-Z]\)/\1 \2/g')

            if [ "$ext" = "mp4" ]; then
              type="video"
            else
              type="image"
            fi

            if [ "$first" = true ]; then
              first=false
            else
              echo "," >> gallery.json
            fi

            echo "  { \"type\": \"$type\", \"src\": \"/$file\", \"title\": \"$title\" }" >> gallery.json
          done
          echo "]" >> gallery.json

      - name: Commit and push gallery.json
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add gallery.json
          git commit -m "Auto-update gallery.json" || echo "No changes"
          git push
